truncate table province_city restart identity;
truncate table province_city_translation restart identity;
truncate table districts restart identity;
truncate table districts_translation restart identity;
truncate table wards restart identity;
truncate table wards_translation restart identity;
truncate table streets restart identity;
truncate table streets_translation restart identity;
ALTER SEQUENCE province_city_id_seq RESTART;
ALTER SEQUENCE province_city_translation_id_seq RESTART;
ALTER SEQUENCE districts_id_seq RESTART;
ALTER SEQUENCE districts_translation_id_seq RESTART;
ALTER SEQUENCE wards_id_seq RESTART;
ALTER SEQUENCE wards_translation_id_seq RESTART;
ALTER SEQUENCE streets_id_seq RESTART;
ALTER SEQUENCE streets_translation_id_seq RESTART;
truncate table customers;
truncate table customer_phones;
truncate table customer_demands;
truncate table brokers;
truncate table broker_phones;
truncate table export_queue;
truncate table import_queue;
truncate table real_estate;
truncate table real_estate_branch;
truncate table real_estate_subscribe;
truncate table real_estate_historical;
SELECT setval('districts_id_seq', (SELECT MAX(id) FROM districts)+1);
SELECT setval('districts_translation_id_seq', (SELECT MAX(id) FROM districts_translation)+1);
SELECT setval('province_city_id_seq', (SELECT MAX(id) FROM province_city)+1);
SELECT setval('province_city_translation_id_seq', (SELECT MAX(id) FROM province_city_translation)+1);
SELECT setval('wards_id_seq', (SELECT MAX(id) FROM wards)+1);
SELECT setval('wards_translation_id_seq', (SELECT MAX(id) FROM wards_translation)+1);
SELECT setval('streets_id_seq', (SELECT MAX(id) FROM streets)+1);
SELECT setval('streets_translation_id_seq', (SELECT MAX(id) FROM streets_translation)+1);