name: tienthanh-api
description: Infrastructure for TienThanh (S4 task 10).
runtime:
  name: nodejs
  options:
    typescript: true
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
